name: Deploy metrics app

on:
  push:
    branches: [ "main", "qa", "dev" ]
    tags: [ "v*.*.*" ]
    paths:
      - metrics_app/**
      - .github/1-metrics-app.yaml
      - .github/0-build-n-push.yaml

jobs:
  call-docker-build:
    uses: ./.github/workflows/0-build-n-push.yaml
    with:
      image-name: tmp-metrics-app
      dockerfile-dir: metrics_app/
    secrets: inherit
