name: Deploy metrics app

on:
  push:
    branches:
      - main
    paths:
      - metrics_app/**

jobs:
  call-docker-build:
    uses: ./.github/workflows/0-build-n-push.yaml
    with:
      image-name: tmp-metrics-app
      dockerfile-path: metrics_app/
    secrets: inherit
