name: Deploy Python backend

on:
  push:
    branches: [ "main", "qa", "dev" ]
    tags: [ "v*.*.*" ]
    paths:
      - python_app/**
      - .github/2-python-app.yaml
      - .github/0-build-n-push.yaml

jobs:
  call-docker-build:
    uses: ./.github/workflows/0-build-n-push.yaml
    with:
      image-name: tmp-python-app
      dockerfile-dir: python_app/
    secrets: inherit
