name: Just o play around

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: Some step
        run: |
          db_password="abcd1234"
          echo "::add-mask::$db_password"
          echo "db_password=$db_password" >> $GITHUB_ENV

      - name: A different step ${{ env.db_password }}
        run: echo $db_password
